services:
  - type: pserv
    name: python-agent
    repo: https://github.com/livekit-examples/agent-deployment

    # This should be a directory, NOT the Dockerfile itself
    rootDir: .  # ⛳ change from "Dockerfile" to "."

    runtime: image
    plan: starter
    region: singapore  # 🔁 Optional: switch to your region if not US

    # Graceful shutdown delay (standard 5 minutes)
    maxShutdownDelaySeconds: 300

    scaling:
      minInstances: 1
      maxInstances: 4
      targetCPUPercent: 60
      targetMemoryPercent: 60

    envVars:
      - fromGroup: agent-env
version: "1"
