services:
  - type: pserv
    name: python-agent
    repo: https://github.com/livekit-examples/agent-deployment
    rootDir: .

    runtime: docker
    plan: starter
    region: singapore

    maxShutdownDelaySeconds: 300

    scaling:
      minInstances: 1
      maxInstances: 4
      targetCPUPercent: 60
      targetMemoryPercent: 60

    envVars:
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DIFY_API_KEY
        sync: false
      - key: DIFY_API_ENDPOINT
        sync: false

version: "1"
