services:
  - type: pserv
    name: python-agent
    repo: https://github.com/livekit-examples/agent-deployment

    rootDir: .

    runtime: docker
    plan: starter
    region: singapore

    # Graceful shutdown delay (standard 5 minutes)
    maxShutdownDelaySeconds: 300

    scaling:
      minInstances: 1
      maxInstances: 4
      targetCPUPercent: 60
      targetMemoryPercent: 60

    envVars:
      - fromGroup: agent-env
version: "1"
